server {
    listen 80;
    server_name _;
    
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;

        gzip_static on;
        add_header Cache-Control no-cache;
        add_header Access-Control-Allow-Origin *;
        expires 0;

        sub_filter '%%%PUBLIC_PATH%%%'  '$http_x_script_name';
        sub_filter '%%%STYLE_NONCE%%%' '$request_id';
        sub_filter_once off;
    }

    location /static/ {
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "public";
        gzip_static on;
        add_header Access-Control-Allow-Origin *;
    }
}
